In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt



In [2]:
print(np.__version__)



2.3.2


In [3]:
np.zeros(3)


array([0., 0., 0.])

In [4]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
print(np.zeros(3).shape,np.zeros((4,5)).shape)

(3,) (4, 5)


In [6]:
np.zeros((4,5)).ndim

2

In [ ]:
import numpy as np

a = np.array([1,2,3])
print(a)



[1 2 3]


home2


In [1]:
import numpy as np

x = np.array([3,4])

def vector_norm(vector):
    squares = [element**2 for element in vector]
    return sum(squares)**0.5

print('Array :',x)
print(vector_norm(x))

Array : [3 4]
5.0


In [3]:
import numpy.linalg as la
la.norm(x)

np.float64(5.0)

In [4]:
y = np.array([5,7])

np.dot(x,y)

np.int64(43)

In [ ]:

x.dot(y)

np.int64(43)

In [6]:
A = np.array([[2,3,4],[1,9,7]])
A

array([[2, 3, 4],
       [1, 9, 7]])

In [7]:
x = np.array([2,3,4]).reshape(-1,1)
x

array([[2],
       [3],
       [4]])